config/routes.rb
Rails.application.routes.draw do

  match '*any' => 'application#options', :via => [:options]

  get 'tracking_calls/' => 'tracking_calls#index'
  get 'tracking_calls/main' => 'tracking_calls/main'
  get 'ui_data/main' => 'ui_data#trax'
  get 'param_data/' => 'param_data#index'
  get 'param_data/main' => 'tracking_calls/main'
  post 'param_data/create_service' => 'param_data#create_service'
  post 'param_data/create_service_fields' => 'param_data#create_service_fields'
  post 'param_data/service_fields' => 'param_data#service_fields'
  post 'param_data/edit_service_fields' => 'param_data#submit_service_fields'
  post 'param_data/edit_field_description' => 'param_data#edit_field_description'
  get 'ui_data/services' => 'ui_data#services_form'

  post 'ui_data/services' => 'ui_data#services'
  get 'ui_data/fields' => 'ui_data#fields_form'
  get 'tracking_calls/new' => 'tracking_calls#new_form'
  post 'tracking_calls/new' => 'tracking_calls#create'
  get 'tracking_calls/search' => 'tracking_calls#search_form'
  post 'tracking_calls/search' =>  'tracking_calls#search'
  get 'tracking_calls/edit_results' =>  'tracking_calls#edit_form'
  post 'tracking_calls/edit_results' =>  'tracking_calls#edit'
  get 'tracking_calls/delete' => 'tracking_calls#delete_form'
  delete 'tracking_calls/delete' =>  'tracking_calls#delete'

  post 'ui_data/search' => 'tracking_calls/search'

  get  'api/tracking_request' => 'tracking_request#search'


  resources :param_data do
    get :autocomplete_field_field_name, :on => :collection

    get :autocomplete_service_name, :on => :collection
  end


  resources :ui_data do
    get :hive_select, on: :collection
  end

   root 'welcome#index'








end

app/controllers/param_data_controller.rb
class ParamDataController < ApplicationController

  autocomplete :field, :field_name

  autocomplete :service, :name

  def create_service
    @errors = ""
    p = data_params
    begin
      begin
        if p.values.to_s == '["", ""]'
          raise "Please supply service name and domain"
        elsif p.values[0] == ""
          raise "Please supply service name"
        elsif p.values[1] == ""
          raise "Please supply domain"
        end
      rescue => e
        to_errors(e.message, "")
        return
      end

      begin
        service = Service.new(p)
        service.save
      rescue => e
        to_errors(e.message, "for service creation")
      end
    ensure
      @error_div = "create_service_errors"
      if @errors.blank?
        to_errors("Service #{service.name} added sucessfully", "")
      end
      render "errors"
    end
  end

  def create_service_fields
      @errors = ""
      fs = field_service_params
      f = field_params
      s = service_params
      service_fields = nil
      @error_div = "create_service_field_errors"
      begin
        begin
          if f.values.to_s == '[""]' && s.values.to_s == '[""]'
            raise "Please supply field and service"
          elsif f.values.to_s == '[""]'
            raise "Please supply field"
          elsif s.values.to_s == '[""]'
            raise "Please supply service"
          end
        rescue => e
          to_errors(e.message, "")
          return
        end
        begin
          field = Field.new(f)
          field.save
        rescue => e
          to_errors(e.message, "for field created")
          return
        end
        begin
          field = Field.where("field_name = ?", f[:field_name])
          service = Service.find_by(name: s[:service])
          service_fields = service.fields
          service_fields << field

        rescue => e
          to_errors(e.message, "for Service/Field association")
          return
        end
        begin
          assoc_description = service.field_service.where("field_id = ?", field[0][:id])
          assoc_description.update_all(fs)
        rescue => e
          to_errors(e.message, "for Service/Field association")
          return
        end
      ensure
        if @errors.blank?
          @errors = ""
           render "errors"
        else
          render "errors"
        end
      end
  end

  def service_fields
    @event_types = EventType.all
    service = Service.find_by(name: params[:edit_service_fields][:service])
    service_field_details = service.fields
    @service_fields = service_field_details.select(:field_name, :description, :event_type).as_json
    @service_fields.each{|h| h["service"] = service[:name]}
    @service_fields.each{|h| h.delete("id")}
  end

  def edit_service_fields
    render "edit_service_fields"

  end

  def submit_service_fields

  end

  def edit_field_description
    @errors = ""
    desc = field_description
    type = event_type
    service = desc_service
    field = desc_field
    begin
      service = Service.find_by(name: service[:service])
      field = Field.find_by(field_name: field[:field])
      assoc = service.field_service.where("field_id = ?", field[:id])
      if params[:commit] == 'Delete Field Association'
        begin
          assoc.delete_all
        rescue => e
          to_errors(e.message, "for deleting association")
        end
      else
        begin
          assoc.update_all(desc)

        rescue => e
          to_errors(e.message, "for edit description")
        end
        begin
           assoc.update_all(type)
        rescue => e
          to_errors(e.message, "for edit click type")
        end
      end
    rescue => e
      to_errors(e.message, "problem with service selected")
    ensure
       @error_div = "edit_description_#{desc[:field]}"
      if @errors.blank?
        @errors = ""
        if params[:commit] == 'Delete Field Association'
          @errors = "Delete successful"
        else
          @errors = "Update successful"
        end
        render "errors"
      else
        render "errors"
      end
    end
  end

  private
  def data_params
    params.require(:service).permit(:service_name, :domain_name)
  end

  def service_params
    params.require(:create_service_fields).permit(:service)
  end

  def field_params
    params.require(:create_service_fields).permit(:field_name)
  end

  def field_service_params
    params.require(:create_service_fields).permit(:description, :event_type)
  end

  def field_description
     params.require(:edit_field_description).permit(:description)
  end

  def event_type
    params.require(:edit_field_description).permit(:event_type)
  end

  def desc_service
    params.require(:edit_field_description).permit(:service)
  end

  def desc_field
    params.require(:edit_field_description).permit(:field)
  end

  def to_errors e, details
    @errors << e.gsub(/^.*Error: /,"").gsub(/\'.*$/,"") << details
  end

  def reload_params
    render :partial => "param_data/create_service_fields"
    render :partial => "param_data/edit_fields"
  end

end

app/views/param_data/_create_service.html.erb
<div id="edit_service_fields" >
  <h3>Add a Service</h1>
  <%= form_for :service, remote:true, method:"post", url:"param_data/create_service" do |f| %>
    <%= f.label :"Enter Service Name", class: "fieldslabel" %>:
    <%= f.text_field :service_name, class: "fieldsinput" %>
    <br>
    <%= f.label :"Domain Name ", class: "fieldslabel" %>:
    <%= f.text_field :domain_name, class: "fieldsinput" %>
    <br>
    <%= f.submit "Add Service", id: "add_service", class: "button" %>
  <% end %>

  <div id="create_service_errors" name="create_service_errors" class="sdiv">
  </div>
</div>

app/views/param_data/_create_service_fields.html.erb
<div id="create_service_fields" class="sdivs">
  <h3> Add a Tracking field  </h3>
  <%= form_for :create_service_fields, remote: "true", method:"post",  url:"param_data/create_service_fields" do |f| %>

    <%= f.label :service, 'Service Name', class: "fieldslabel"  %>
    <% options = options_from_collection_for_select(@services, 'name', 'name' ) %>
    <%= f.select :service,  options, {:prompt => "Select a Service"}, class: "selections" %><br>


    <%= f.label :field_name, class: "fieldslabel" %>
    <%= f.autocomplete_field :field_name, autocomplete_field_field_name_param_data_path, 'data-auto-focus' => true, 'min-length' => 0, class: "fieldsinput" %>
    <%= f.label :auto_complete, class: "sm_text" %><br>

    <%= f.label :description, 'Description', class: "fieldslabel"  %>
    <%= f.text_field :description, class: "fieldsinput" %><br>

    <%= f.label :event_type, 'Click Type', class: "fieldslabel"  %>
    <% type_options = options_from_collection_for_select(@event_types, 'id', 'name' ) %>
    <%= f.select :event_type,  type_options, {:prompt => "Select a Click Type"}, class: "selections" %><br>

    <%= f.submit "Add Service Field", class: "button" %>
  <% end %>
    <div id="create_service_field_errors" name="create_service_field_errors" class="sdiv">
    </div>
</div>

app/views/param_data/_edit_fields.html.erb
<% @service_fields.each do |field| %>
  <div id=<%="#{field['field_name']}"%> >
  <%= form_for :edit_field_description, remote: "true", method:"post",  url:"param_data/edit_field_description" do |f| %>
  <%= f.label :"#{field['field_name']}", "#{field['field_name']}  :  ", class: "important_fieldslabel" %>
  <br>
  <%= f.label :description, 'Description', class: "fieldslabel" %>
  <%= f.text_field :description, value: "#{field['description']}", size: 20, class: "fieldsinput" %>
  <br>
  <%= f.label :event_type, 'Click Type', class: "fieldslabel"  %>
  <% options = options_from_collection_for_select(@event_types, 'id', 'name',{:selected => "#{field['event_type']}", :prompt => true} ) %>
  <%= f.select :event_type,  options, {:prompt => "Select a Click Type"}, class: "fieldsinput" %>
  <br>
  <%= f.hidden_field :service, :value => "#{field['service']}" %>
  <%= f.hidden_field :field, :value => "#{field['field_name']}" %>
  <br>
  <%= f.submit "Update Field Association Details", class: "button" %>
  <%= f.submit "Delete Field Association", class: "button" %>
  <% end %>
  <br>
  <div id=<%= "edit_description_#{field[1]}" %> >
  </div>
  </div>
<% end %>

app/views/param_data/_errors.html.erb
<pre style="color:red; font-weight: bold; font-size: large; font-style: italic; font-family: arial" >
     <%= @errors %>
</pre>

app/views/param_data/_main.html.erb
<div id="container" >
  <div id="top-section" class="container" >
    <div id="left" class="tc_left" >
      <%= render "param_data/create_service" %>
      <%= render "param_data/create_service_fields", service_fields: @service_fields %>
    </div>
  </div>
  <div id="right" class="tc_right" >
    <%= render "param_data/service_fields", service_fields: @service_fields %>
  </div>
</div>

app/views/param_data/_service_fields.html.erb
<div id="edit_service_fields" >
  <%= form_for :edit_service_fields, remote: "true", method:"post",  url:"param_data/service_fields", :html=>{:id=>'service_fields'} do |f| %>
    <%= f.label :edit_service_fields, 'Providers'  %>
    <% options = options_from_collection_for_select(@services, 'name', 'name' ) %>
    <%= f.select :service,  options, {:prompt => "Select a Service"}, :onchange => "$('#service_fields').submit();" %>
  <% end %>

  <div id="edit_fields" name="edit_fields" >
  </div>
  <div id="edit_field_errors" name="edit_field_errors">
  </div>
</div>

app/views/param_data/errors.js.erb
$("#<%= @error_div %>").html('<%= escape_javascript( render :partial => "errors" ) %>');

app/views/param_data/main.html.erb
<div id="container" >
  <p> This space will soon serve to support creates, edits and deletes of tracking parameters and their mapping to their associated services </p>
</div>

app/views/param_data/service_fields.js.erb
$('#edit_fields').html('<%= escape_javascript( render :partial => "param_data/edit_fields" ) %>');